// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityWebSite.DataAccess.Concrete.Contexts;

namespace UniversityWebSite.DataAccess.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20211228143422_addedSeedData")]
    partial class addedSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Paragraph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456a",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AboutId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavBarHeader")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 553, DateTimeKind.Local).AddTicks(5352),
                            Name = "Düzce",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2162),
                            Name = "Kuruluş",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2189),
                            Name = "Yönetim",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2191),
                            Name = "Sayılarla DÜ",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2249),
                            Name = "Sıralamalar",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2251),
                            Name = "İlkler",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2258),
                            Name = "Kurumsal Strateji",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2260),
                            Name = "İdari Birimler",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2261),
                            Name = "Fakülteler",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2262),
                            Name = "Enstitüler",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2263),
                            Name = "Yüksekokullar",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2264),
                            Name = "Meslek Yüksekokulları",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2265),
                            Name = "Kurullar",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2266),
                            Name = "Bölüm Başkanlıkları",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2267),
                            Name = "Araştırma Merkezleri",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2269),
                            Name = "Laboratuvar Envanteri",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2270),
                            Name = "Yayınlar/Projeler",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2271),
                            Name = "Hakemli Dergiler",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2272),
                            Name = "Teknoloji Transfer Ofisi",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2273),
                            Name = "Tıbbi Bitki Yetiştiriciliği",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2274),
                            Name = "Ürünler/Markalar",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2275),
                            Name = "Üretim Merkezi",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 23,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2276),
                            Name = "Bilimsel Yayınlar",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2277),
                            Name = "İşbirlikleri",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 25,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2278),
                            Name = "Etkinlikler",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2279),
                            Name = "E-Posta",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 27,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2280),
                            Name = "EBYS",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 28,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2281),
                            Name = "ÖBS/KYBS",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 29,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2282),
                            Name = "UZEM",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2283),
                            Name = "Kütüphane",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 31,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2284),
                            Name = "Rehber",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 32,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2285),
                            Name = "PBS",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 33,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2286),
                            Name = "Staj",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 34,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2287),
                            Name = "Havuz",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 35,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2288),
                            Name = "Yemek Menüsü",
                            NavBarHeader = 4
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfFaculty")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfProject")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeacher")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Subtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subtitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(2853),
                            Name = "Rektör"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3258),
                            Name = "Rektör Yardımcıları"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3261),
                            Name = "Senato"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3262),
                            Name = "Yönetim Kurulu"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3264),
                            Name = "Öğrenci Sayıları"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3265),
                            Name = "Personel Sayıları"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3266),
                            Name = "Proje Sayıları"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3267),
                            Name = "Fikri Mülkiyet"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3269),
                            Name = "URAP"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3273),
                            Name = "THE"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3274),
                            Name = "Green Metric"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3275),
                            Name = "InnovaLig"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3276),
                            Name = "Stratejik Plan"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3277),
                            Name = "Kalite Politikası"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3278),
                            Name = "Sürekli İyileştirme"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3280),
                            Name = "Sürdürülebilirlik Raporu"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3281),
                            Name = "Eğitim Fakültesi"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3282),
                            Name = "Mühendislik Fakültesi"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3284),
                            Name = "Tıp Fakültesi"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3285),
                            Name = "Fen Edebiyat Fakültesi"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3286),
                            Name = "Güzel Sanatlar Enstitüsü"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3287),
                            Name = "Fen Bilimleri Enstitüsü"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3288),
                            Name = "Sağlık Bilimleri Enstitüsü"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3290),
                            Name = "Sosyal Bilimler Enstitüsü"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 11,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3291),
                            Name = "Akçakoca Turizm İşletme"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 11,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3292),
                            Name = "Hakime Erciyas Yabancı Diller"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3293),
                            Name = "Akçakoca MYO"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3295),
                            Name = "Çilimli MYO"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3296),
                            Name = "Düzce MYO"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3297),
                            Name = "Gölyaka MYO"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 14,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3298),
                            Name = "Atatürk İlkeleri ve İnkılap Tarihi"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 14,
                            CreatedTime = new DateTime(2021, 12, 28, 17, 34, 21, 554, DateTimeKind.Local).AddTicks(3299),
                            Name = "Türk Dili"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Box", b =>
                {
                    b.HasOne("UniversityWebSite.Entities.Concrete.About", "About")
                        .WithMany("Boxes")
                        .HasForeignKey("AboutId");

                    b.Navigation("About");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Subtitle", b =>
                {
                    b.HasOne("UniversityWebSite.Entities.Concrete.Category", "Category")
                        .WithMany("Subtitles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.About", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Subtitles");
                });
#pragma warning restore 612, 618
        }
    }
}
