// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityWebSite.DataAccess.Concrete.Contexts;

namespace UniversityWebSite.DataAccess.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20211230094100_addAnotherSeedData")]
    partial class addAnotherSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Paragraph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(592),
                            Paragraph = "Üniversitemizde öğrencilerimizin istedikleri alanda özelleşmelerine olanak sağlayan geniş yelpazeli seçmeli ders seçenekleri sunulmaktadır. Dileyen öğrencilerimiz diğer bölüm programlarıyla yandal ve çift anadal eğitimi alabilme imkânına sahiptir. Öğrencilerimize ilaveten Erasmus Öğrenci Değişim Programı kapsamında yurt dışında anlaşmalı olduğumuz üniversitelerde burslu eğitim alma imkânı da sağlanmaktadır. Bu program dahilinde öğrencilerimiz eğitimlerine bir veya iki dönem Avrupa’da devam edebilmektedirler."
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456a",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AboutId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("Boxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutId = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(951),
                            Header = "Nitelikli akademik kadro",
                            Text = "Mesleki bilgileri kazanım için bir bölümdeki en önemli unsur öğretim kadrosudur."
                        },
                        new
                        {
                            Id = 2,
                            AboutId = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(1350),
                            Header = "Güncel eğitim programı ve ders içerikleri",
                            Text = "Dünyadaki eğilime uygun olarak bir endüstri mühendisine kazandırılması gereken yetkinlikler dikkate alınarak eğitim programı tasarlanmıştır."
                        },
                        new
                        {
                            Id = 3,
                            AboutId = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(1352),
                            Header = "Öğrencinin sosyal, kültürel ve spor faaliyetleri",
                            Text = "Kampüsümüzde devlet tiyatrosu mevcut olup burada tiyatro ve sanatsal etkinlikler düzenlenmektedir. Yine olimpik yüzme havuzunu, dans salonlarını, kapalı spor salonunu, tekno fitness salonunu içeren Türkiye’nin en büyük kapalı spor merkezi üniversitemizde mevcuttur."
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavBarHeader")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(495),
                            Name = "Düzce",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7106),
                            Name = "Kuruluş",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7124),
                            Name = "Yönetim",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7126),
                            Name = "Sayılarla DÜ",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7128),
                            Name = "Sıralamalar",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7129),
                            Name = "İlkler",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7130),
                            Name = "Kurumsal Strateji",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7131),
                            Name = "İdari Birimler",
                            NavBarHeader = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7132),
                            Name = "Fakülteler",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7133),
                            Name = "Enstitüler",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7134),
                            Name = "Yüksekokullar",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7135),
                            Name = "Meslek Yüksekokulları",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7136),
                            Name = "Kurullar",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7137),
                            Name = "Bölüm Başkanlıkları",
                            NavBarHeader = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7138),
                            Name = "Araştırma Merkezleri",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7139),
                            Name = "Laboratuvar Envanteri",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7170),
                            Name = "Yayınlar/Projeler",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7171),
                            Name = "Hakemli Dergiler",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7172),
                            Name = "Teknoloji Transfer Ofisi",
                            NavBarHeader = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7173),
                            Name = "Tıbbi Bitki Yetiştiriciliği",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7174),
                            Name = "Ürünler/Markalar",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7175),
                            Name = "Üretim Merkezi",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 23,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7177),
                            Name = "Bilimsel Yayınlar",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7178),
                            Name = "İşbirlikleri",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 25,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7179),
                            Name = "Etkinlikler",
                            NavBarHeader = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7180),
                            Name = "E-Posta",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 27,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7181),
                            Name = "EBYS",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 28,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7182),
                            Name = "ÖBS/KYBS",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 29,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7183),
                            Name = "UZEM",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7184),
                            Name = "Kütüphane",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 31,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7185),
                            Name = "Rehber",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 32,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7186),
                            Name = "PBS",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 33,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7187),
                            Name = "Staj",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 34,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7188),
                            Name = "Havuz",
                            NavBarHeader = 4
                        },
                        new
                        {
                            Id = 35,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7189),
                            Name = "Yemek Menüsü",
                            NavBarHeader = 4
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(9224),
                            Email = "du@edu.tr",
                            Fax = "+90 (380) 5421103",
                            Phone = "+90 850 800 8181"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Keywords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8595),
                            Title = "Mühendislik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8784),
                            Title = "Tıp"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8787),
                            Title = "Ziraat"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8788),
                            Title = "Eğitim"
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8789),
                            Title = "Fen Edebiyat"
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8791),
                            Title = "Mimarlık"
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8792),
                            Title = "İşletme"
                        },
                        new
                        {
                            Id = 8,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8793),
                            Title = "Orman"
                        },
                        new
                        {
                            Id = 9,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8794),
                            Title = "Sağlık Bilimleri"
                        },
                        new
                        {
                            Id = 10,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8795),
                            Title = "Spor Bilimleri"
                        },
                        new
                        {
                            Id = 11,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8796),
                            Title = "Eğitim"
                        },
                        new
                        {
                            Id = 12,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(8797),
                            Title = "Siyasal Bilgiler"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(1582),
                            Url = "https://studyinturkey.net/wp-content/uploads/2021/01/duzce-universitesi-kampus.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(1719),
                            Url = "https://static.daktilo.com/sites/622/uploads/2021/06/07/whatsapp-image-2021-06-07-at-164152-1.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(1722),
                            Url = "https://pbs.twimg.com/media/FDa851KWUAEoNpt?format=jpg&name=large"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfFaculty")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfProject")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeacher")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(9888),
                            NumberOfFaculty = 12,
                            NumberOfProject = 1231,
                            NumberOfStudent = 17592,
                            NumberOfTeacher = 1275
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Subtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subtitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7606),
                            Name = "Rektör"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7937),
                            Name = "Rektör Yardımcıları"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7940),
                            Name = "Senato"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7941),
                            Name = "Yönetim Kurulu"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7942),
                            Name = "Öğrenci Sayıları"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7943),
                            Name = "Personel Sayıları"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7946),
                            Name = "Proje Sayıları"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7948),
                            Name = "Fikri Mülkiyet"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7949),
                            Name = "URAP"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7950),
                            Name = "THE"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7951),
                            Name = "Green Metric"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7952),
                            Name = "InnovaLig"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7954),
                            Name = "Stratejik Plan"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7955),
                            Name = "Kalite Politikası"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7956),
                            Name = "Sürekli İyileştirme"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7957),
                            Name = "Sürdürülebilirlik Raporu"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7958),
                            Name = "Eğitim Fakültesi"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7959),
                            Name = "Mühendislik Fakültesi"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7960),
                            Name = "Tıp Fakültesi"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 9,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7961),
                            Name = "Fen Edebiyat Fakültesi"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7962),
                            Name = "Güzel Sanatlar Enstitüsü"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7963),
                            Name = "Fen Bilimleri Enstitüsü"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7965),
                            Name = "Sağlık Bilimleri Enstitüsü"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7966),
                            Name = "Sosyal Bilimler Enstitüsü"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 11,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7967),
                            Name = "Akçakoca Turizm İşletme"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 11,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7968),
                            Name = "Hakime Erciyas Yabancı Diller"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7969),
                            Name = "Akçakoca MYO"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7970),
                            Name = "Çilimli MYO"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7971),
                            Name = "Düzce MYO"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 12,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7972),
                            Name = "Gölyaka MYO"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 14,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7973),
                            Name = "Atatürk İlkeleri ve İnkılap Tarihi"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 14,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 645, DateTimeKind.Local).AddTicks(7974),
                            Name = "Türk Dili"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(1953),
                            Title = "DÜ Tanıtım Filmi 2021",
                            Url = "mSS-tfXDrT4"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(2209),
                            Title = "DÜ Tanıtım Filmi 2018",
                            Url = "-myyQEpicLY"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2021, 12, 30, 12, 40, 59, 646, DateTimeKind.Local).AddTicks(2211),
                            Title = "DÜ 15. Yıl Özel Belgeseli",
                            Url = "z2hqyvV6Me0"
                        });
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Box", b =>
                {
                    b.HasOne("UniversityWebSite.Entities.Concrete.About", "About")
                        .WithMany("Boxes")
                        .HasForeignKey("AboutId");

                    b.Navigation("About");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Subtitle", b =>
                {
                    b.HasOne("UniversityWebSite.Entities.Concrete.Category", "Category")
                        .WithMany("Subtitles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.About", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("UniversityWebSite.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Subtitles");
                });
#pragma warning restore 612, 618
        }
    }
}
